name: 'Versioning Job'
description: 'Create a new version based on the commit messages'

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Install semantic-release extra plugins
      run: npm install -g conventional-changelog-conventionalcommits @semantic-release/git @semantic-release/changelog semantic-release@21
      shell: bash
    - name: Create .releaserc
      run: |
        cat <<EOF > .releaserc
        {
          "branches": [
            "$default-branch"
          ],
          "plugins": [
            [
              "@semantic-release/commit-analyzer",
              {
                "preset": "conventionalcommits"
              }
            ],
            "@semantic-release/changelog",
            "@semantic-release/release-notes-generator",
            [
              "@semantic-release/git",
              {
                "assets": ["CHANGELOG.md"]
              }
            ]
          ]
        }
        EOF
      shell: bash
    - name: Release
      run: semantic-release
      shell: bash